const Paginacion = {
    MIN_PAGINACION: 0,
    MAX_PAGINACION_EMPLEADOS: 15,
    MAX_PAGINACION_PRODUCTOS: 25,
    MAX_PAGINACION_CONTRATOS: 15,
    MAX_PAGINACION_DEPARTAMENTOS: 15,

    DEFAULT_CANTIDAD_PAGINACION: 10,
    DEFAULT_PAGINA: 0,

    PARAMETROS_PERMITIDOS: ['cantidad', 'pagina'],
}

export default Paginacion;